version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    networks:
      - minden-network
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_ROOT_PASSWORD
      - POSTGRES_DB=$PG_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    build: .
    restart: on-failure
    env_file: ./.env
    networks:
      - minden-network
    ports:
      - "${APP_LOCAL_PORT}:${APP_DOCKER_PORT}"
    environment:
      - db-url=jdbc:postgresql://localhost:5432/$PG_DATABASE
      - db-user=$PG_USER
      - db-password=$PG_ROOT_PASSWORD
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

networks:
  minden-network:
    driver: bridge

volumes:
  postgres_data: