version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_ROOT_PASSWORD
      - POSTGRES_DB=$PG_DATABASE
    ports:
      - ${PG_LOCAL_PORT}:${PG_DOCKER_PORT}
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - ${APP_LOCAL_PORT}:${APP_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:$PG_DOCKER_PORT/$PG_DATABASE",
        "spring.datasource.username" : "$PG_USER",
        "spring.datasource.password" : "$PG_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: